<?php

namespace app\controller;

use app\controller\common\LogHelper;
use app\BaseController;


class Base extends BaseController
{
    public static $user;

    public function initialize()
    {
        $this->user_info();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function user_info()
    {
        try {
            $token = $this->request->header('x-csrf-token');
            if (empty($token)) $token = $this->request->post('token');
            
            if (empty($token)) {
                LogHelper::error('Token不存在');
                self::$user = null;
                return;
            }
            
            // 验证token
            $res = HomeTokenModel::auth_token($token);
            if (empty($res)) {
                LogHelper::error('Token验证失败', ['token' => substr($token, 0, 10) . '...']);
                self::$user = null;
                return;
            }
            
            // 查询用户信息
            $user_info = UserModel::page_one($res['user_id']);
            if (empty($user_info) || $user_info['status'] != 1) {
                LogHelper::error('用户不存在或状态异常', ['user_id' => $res['user_id']]);
                self::$user = null;
                return;
            }
            
            // 设置用户信息
            self::$user = $user_info;
            
            LogHelper::debug('用户认证成功', [
                'user_id' => $user_info['id'],
                'user_name' => $user_info['user_name']
            ]);
            
        } catch (\Exception $e) {
            LogHelper::error('用户认证异常', ['error' => $e->getMessage()]);
            self::$user = null;
        }
    }

}